//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "jobs")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub employer_admin_id: i32,
    pub industry_id: i32,
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub demand: i32,
    pub start_time: DateTime,
    pub end_time: DateTime,
    pub hourly_rate: Decimal,
    pub required_gender: i16,
    pub required_ages: Json,
    pub required_languages: Json,
    pub required_nationalities: Json,
    pub status: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
