//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

pub use super::articles::Entity as Articles;
pub use super::comments::Entity as Comments;
pub use super::jobs::Entity as Jobs;
pub use super::users::Entity as Users;
